# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

palette = "catppuccin_mocha"

###########################
# pastel powerline prompt #
###########################

format = """
[\ue0b6](fg:mauve)\
[$username ](fg:base bg:mauve)\

[\ue0c6](fg:mauve bg:red)\
[ $directory ](fg:base bg:red)\

[\ue0c6](fg:red bg:maroon)\
[( $git_branch $git_status )](fg:base bg:maroon)\

[\ue0c6](fg:maroon bg:peach)\
[(( $python)( $golang)( $nodejs)( $rust) )](fg:base bg:peach)\

[\ue0c6](fg:peach bg:yellow)\
[ $status ](fg:blue bg:yellow)\

[\ue0b0](fg:yellow bg:#1d2021)\
[ $time( - $cmd_duration) ](fg:text bg:#1d2021)\
[\ue0b0 ](fg:#1d2021)\

$line_break\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "base bold bg:mauve"
style_root = "red bold bg:mauve"
format = '[]($style)'

[directory]
format = "$path"
truncate_to_repo = true
home_symbol = ""
truncation_length = 0
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
format = '$symbol $branch'

[git_status]
format = '$all_status$ahead_behind'

[python]
symbol=""
format = '$symbol( $version)( $virtualenv)'

[golang]
symbol = ""
format = '$symbol( $version)'

[nodejs]
symbol = ""
format = '$symbol( $version)'

[rust]
symbol = ""
format = '$symbol( $version)'

[cmd_duration]
show_milliseconds = true
min_time = 500
# show_notifications = true
# min_time_to_notify = 5000
format = '$duration'

[status]
disabled = false
style = "bg:yellow"
success_symbol = "[](fg:base $style)"
symbol = "[](bold red $style)"
format = '$symbol[( $common_meaning$signal_name$maybe_int)](bold red $style)'
map_symbol = true

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '$time'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = true

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[kubernetes.user_aliases]
"dev.local.cluster.k8s" = "dev"
"root/.*" = "root"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"